--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DeadZeta/RAuth
build-by-default: true
branches:
- master
projects:
  RAuth:
    path: ""
    icon: "/icon.png"
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
...
