name: RAuth
main: DeadZeta\RAuth\Main
api: 2.0.0
mcpe-protocol: 407
version: 1.3.4-Fork
author: DeadZeta
website: deadzeta.ml

commands:
  register:
    default: true
    description: Регистрация на сервере
  login:
    default: true
    description: Авторизация на сервере через IP
  achpw:
    default: true
    description: Смена пароля