name: RAuth
main: DeadZeta\RAuth\Main
api: 3.14.2
version: 1.3.4
author: DeadZeta
website: deadzeta.ml

depend:
- AutoRestarter

commands:
  register:
    default: true
    description: Player Registration on the Server
  login:
    default: true
    description: Player Authorization on IP Server
  achpw:
    default: true
    description: Player Password Change
