name: RAuth
main: RAuth\Main
api: 3.14.2
mcpe-protocol: 407
version: 1.3.2
author: DeadZeta
website: deadzeta.ml

commands:
  register:
    default: true
    description: Player Registration on the Server
  login:
    default: true
    description: Player Authorization on IP Server
  achpw:
    default: true
    description: Player Password Change