---
settings:
  # Количество не правильных паролей.
  max_wrongs: 5
  # Время бана игрока который ввел не правильный пароль (минуты).
  max_wrongs_time: 5
  # Количество входов с 1 IP адреса (Если на сервере не стоит АвтоПерезагрузка, то поставьте как минимум 10000 входов xD). БотФильтер
  max_joins: 25
  # Время данное игроку чтобы авторизоватся/зарегистрироватся (секунды).
  timeout: 120

# Провайдеры: SQLITE, MYSQL
provider: SQLITE

# MYSQL данные
mysql_data:
  host: 127.0.0.1
  user: yourUser
  password: yourPassword
  base: yourDataBase
  port: 3306
...